// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/
 int as_rightHandMasteryBuff;
 int as_leftHandMasteryBuff;
 int tf_doubleAttackEnableCritical;
 int as_katarMasteryCritBonus;
 int as_splasherRenewalSetting;
 int kn_spearMasteryAspdBuff;
 int pr_maceMasteryAspdBuff;
 int cr_spearQuickenBuff;
 int sa_autoSpellBuff;
